version: 2.1
jobs:
  build:
    branches:
      only:
        - master
    working_directory: ~/code
    environment:
      - TERM: dumb
      - MAX_HEAP_SIZE: 2048m

      - ANDROID_COMPILE_VERSION: 28

      - _JAVA_OPTS: -Xmx$MAX_HEAP_SIZE

    docker:
      - image: circleci/android:api-$ANDROID_COMPILE_VERSION-alpha

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Accept licences 1
          command: yes | sdkmanager --licenses || exit 0
      - run:
          name: Accept licences 2
          command: yes | sdkmanager --update || exit 0
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Lint
          command: ./gradlew lint
      - run:
          name: Build lib
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs
          destination: outputs
      - store_artifacts:
          path: app/build/reports
          destination: reports

