name: Build, Test and Deploy
on:
  push:
    branches:
      - master
      - qa

jobs:
  tag:
    name: Create Tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag_version.outputs.new_tag }}
      version: ${{ steps.tag_version.outputs.new_version }}
      changelog: ${{ steps.tag_version.outputs.changelog }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          pre_release_branches: qa
          append_to_pre_release_tag: rc
          github_token: ${{ github.token }}

  build:
    name: Build & Deploy
    needs: tag
    runs-on: ubuntu-latest
    env:
      VERSION_NUM: ${{ needs.tag.outputs.version }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Env
        run: echo "BUILD_NUM=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Version Infos
        run: echo $VERSION_NUM && echo $BUILD_NUM && echo '${{ needs.tag.outputs.changelog }}'

      - name: Update Changelogs
        run: echo '${{ needs.tag.outputs.changelog }}' > release_note.txt

      - name: Setup JAVA
        uses: actions/setup-java@v2
        with:
          java-version: '12'
          distribution: 'zulu'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle
          key: jars-{{ hashFiles("build.gradle") }}-{{ hashFiles("app/build.gradle") }}
          restore-keys: jars-

      - name: Build
        run: ./gradlew lint && ./gradlew assembleRelease

      - name: Make Github Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.tag.outputs.tag }}
          prerelease: ${{ github.ref == 'refs/heads/qa' }}
          body_path: release_note.txt
          files: |
            app/build/outputs/aar/*.aar

      - name: Clean
        if: ${{ failure() || cancelled() }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          tag_name: ${{ needs.tag.outputs.tag }}
